[workspace]
resolver = "2"
members = [
    "day01",
    "day02",
    "day03",
]

[workspace.package]
edition = "2021"
authors = ["Your Name"]

[workspace.dependencies]
# Add shared dependencies here that multiple days might use
# Example: itertools = "0.12"

